#! /bin/sh

# Restore wallpaper
~/.fehbg
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d '一' '二' '三' '四' '五' '六' '七'
		bspc monitor ${monitor} -n "$name" -d I II III IV V VI VII VIII IX X
		let name++
	done
}
workspaces

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#a6e3a1"
bspc config normal_border_color "#1e1e2e"
bspc config active_border_color "#f38ba8"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
declare -a terminal=()
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(discord spotify)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code terminal)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done


## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww

# Launch Conkeww
#sed -i "s/colors\/color-.*/colors\/color-tokyo.yuck\")/g" $HOME/.config/conkeww/eww.yuck
#eww --config $HOME/.config/conkeww/ open conkeww-main

# Launch notification daemon
dunst -config $HOME/.config/dunst/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
#    /usr/lib/xfce-polkit/xfce-polkit &
#fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/picom/picom.conf &

# start mpd
mpd &

#start asus rog control center
rog-control-center

#start oneko
oneko

# replace neovim colorscheme
#sed -i "s/theme =.*$/theme = \"pastelDark\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc
